name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Get inputs
      run: git clone git@github.com:astaugaard/aoc2024-inputs.git
    - name: Move inputs
      run: mv aoc2024-inputs inputs
    - name: Run tests
      run: cargo test --verbose --release
    - name: remove inputs idk if needed
      run: rm -rf inputs
